name: Build Executables

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: "Dreamland-${{ github.ref_name }}"

jobs:
  windows-export:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          cp .github/workflows/export_presets.cfg export_presets.cfg
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --path . --no-window --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows-${{ env.EXPORT_NAME }}
          path: build/windows/${{ env.EXPORT_NAME }}.exe
