name: Build Executables

on:
  push:
    branches: [ "master", "bigdavisc-auto-builds" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: "Dreamland-$GITHUB_REF_NAME"

jobs:
  windows-export:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci@3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows
          path: build/windows
